-- Member code: a short, immutable, per-account identifier shown on the user's
-- /account page and in the admin table. Joey uses it as the canonical handle
-- when granting promos / comps over DM — the user shares their code, he looks
-- it up, no fishing through emails.
--
-- Format: 7 chars from a 31-char alphabet (digits + uppercase, minus 0/1/I/L/O
-- to avoid visual ambiguity when read aloud or typed). ~27.5B combinations.
-- Generated server-side on insert; immutable thereafter (lock trigger below).

alter table profiles
  add column member_code text;

create or replace function gen_member_code()
returns text language plpgsql as $$
declare
  alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  result text := '';
  i int;
begin
  for i in 1..7 loop
    result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return result;
end$$;

-- Assign a unique code to a profile that doesn't have one yet. Retries on
-- collision up to 12 times; at 27B combos a collision is vanishingly rare
-- but we still want a deterministic failure mode rather than an infinite loop.
create or replace function assign_member_code(p_id uuid)
returns text language plpgsql as $$
declare
  candidate text;
  existing text;
  attempts int := 0;
begin
  select member_code into existing from profiles where id = p_id;
  if existing is not null then return existing; end if;

  loop
    candidate := gen_member_code();
    begin
      update profiles set member_code = candidate where id = p_id;
      return candidate;
    exception when unique_violation then
      attempts := attempts + 1;
      if attempts > 12 then
        raise exception 'could not generate unique member_code after % attempts', attempts;
      end if;
    end;
  end loop;
end$$;

-- Backfill existing accounts.
do $$
declare p record;
begin
  for p in select id from profiles where member_code is null loop
    perform assign_member_code(p.id);
  end loop;
end$$;

-- Lock the column once it's set and enforce uniqueness now that backfill is done.
alter table profiles
  alter column member_code set not null;

create unique index profiles_member_code_key on profiles(member_code);

create or replace function lock_member_code()
returns trigger language plpgsql as $$
begin
  if old.member_code is not null and new.member_code is distinct from old.member_code then
    raise exception 'member_code is immutable';
  end if;
  return new;
end$$;

drop trigger if exists lock_member_code_trg on profiles;
create trigger lock_member_code_trg
  before update on profiles
  for each row execute function lock_member_code();

-- New signups get a code generated by handle_new_user(). We re-define the
-- whole function rather than chaining a second trigger so the code lands in
-- the same row insert (one fewer round-trip on signup).
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  candidate text;
  attempts int := 0;
begin
  loop
    candidate := gen_member_code();
    begin
      insert into profiles (id, display_name, member_code)
      values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email), candidate);
      return new;
    exception when unique_violation then
      attempts := attempts + 1;
      if attempts > 12 then
        raise exception 'could not generate unique member_code on signup after % attempts', attempts;
      end if;
    end;
  end loop;
end;
$$;

notify pgrst, 'reload schema';
