// The Dispatch — editorial changelog for the Clubhouse. One module so the
// Front Desk "from the wire" teaser and the full /hub/whats-new timeline
// never drift apart. Newest first.
//
// status: 'new'  → shipped, dated entry
//         'soon' → on the way; date is the window, not a promise

export type DispatchEntry = {
  id: string
  date: string // display string, e.g. 'Jun 9, 2026'
  title: string
  /** Italic-gold tail of the title, e.g. 'four rooms.' */
  titleEm?: string
  body: string
  status: 'new' | 'soon'
  tags: { label: string; tone?: 'gold' | 'rust' | 'steel' }[]
}

export const COMING_SOON: DispatchEntry[] = [
  {
    id: 'sunday-live',
    date: 'TBD',
    title: 'Sunday Live,',
    titleEm: 'back in the booth.',
    body: 'The game-day broadcast is off the air while we rebuild it to run lighter. Every matchup live, real NFL scoreboards, and a storyline engine calling the swings as they happen is a lot of data to move every few minutes for every league at once, so it stays in the workshop until it can do that without slowing down the rest of the site.',
    status: 'soon',
    tags: [{ label: 'Game day', tone: 'steel' }, { label: 'In the works', tone: 'rust' }],
  },
  {
    id: 'mobile-rooms',
    date: '2026 season',
    title: 'The last desktop rooms,',
    titleEm: 'on your phone.',
    body: 'The Chart Room, the Mock Room, and the Hall’s new filters still only open properly on a laptop. Phone builds are next in line, the same way the All-Time Team and the Draft Grader made the trip.',
    status: 'soon',
    tags: [{ label: 'Mobile', tone: 'steel' }, { label: 'In the works', tone: 'rust' }],
  },
  {
    id: 'the-field',
    date: 'Later in 2026',
    title: 'The',
    titleEm: 'Field.',
    body: 'A public, cross-league view of the player pool: start rates, roster rates, and trade velocity drawn from every league on TSC, across all four platforms at once. See how your league’s reads compare to everyone else’s.',
    status: 'soon',
    tags: [{ label: 'Public page', tone: 'steel' }, { label: 'In the works', tone: 'rust' }],
  },
  {
    id: 'underdog',
    date: 'TBD',
    title: 'A fifth',
    titleEm: 'platform.',
    body: 'Underdog Fantasy is on the integration bench. Same promise as the other four: bring a league ID, get the whole history back.',
    status: 'soon',
    tags: [{ label: 'Platforms', tone: 'steel' }],
  },
]

export const DISPATCH: DispatchEntry[] = [
  {
    id: 'season-rules-eras',
    date: 'Sep 29, 2026',
    title: 'Your league’s rules,',
    titleEm: 'year by year.',
    body: 'Leagues change their rules, and the record book now knows it. Commissioners can set each season’s playoff format and scoring on the Sources page (prefilled from Sleeper and ESPN), then group seasons into eras. The Record Book and Standings now filter by regular season or playoffs, by era, or by any run of years. Two-week playoff rounds are split into their real weeks too, so a 280-point “week” no longer tops the single-week records.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Almanac' }, { label: 'Commissioners' }],
  },
  {
    id: 'commish-power',
    date: 'Sep 29, 2026',
    title: 'The commish’s',
    titleEm: 'power rankings.',
    body: 'Commissioners can now publish their own power rankings every week, drag and drop with a note, straight from the Current Season page. The public Power Rankings page flips between the model’s order and the commish’s, and a new section calls out where the two disagree the most.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Live season' }, { label: 'Commissioners' }],
  },
  {
    id: 'trade-desk-in-season',
    date: 'Sep 29, 2026',
    title: 'The Trade Desk,',
    titleEm: 'in-season tune-up.',
    body: 'Trades now sync twice a day and grade themselves on a schedule that actually runs. TE premium leagues price tight ends on a curve, so the elite ones gain the most instead of every TE getting the same flat bump. Every trade is dated to its real NFL week, which puts the position-rank chips (RB12 to RB8) back on trades from every platform. The Rumor Mill’s written columns and the Analyzer’s verdicts are back after our AI provider retired the model behind them, and the Rumor Mill got its own share card.',
    status: 'new',
    tags: [{ label: 'Live season' }, { label: 'Trade Desk' }, { label: 'Fixes' }],
  },
  {
    id: 'season-runs-itself',
    date: 'Sep 25, 2026',
    title: 'The season',
    titleEm: 'runs itself.',
    body: 'Once the NFL kicks off, a league now flips to the current season on its own, and the week rolls over every Tuesday without anyone touching it. A sync no longer wipes the current week, a commissioner’s week override keeps advancing instead of freezing the league in place, and Pick’ems lock on time at 8pm ET Thursday. The weekly refresh moved to Tuesday morning so Monday night is always in it. And no ESPN league crowns a 2-0 team as its reigning champion in Week 3 anymore.',
    status: 'new',
    tags: [{ label: 'Live season' }, { label: 'Fixes' }],
  },
  {
    id: 'out-of-testing',
    date: 'Sep 17, 2026',
    title: 'Out of',
    titleEm: 'testing.',
    body: 'The free testing window closed on September 17 and The Sunday Chronicle is officially open. Thank you to everyone who synced a league, broke something, and wrote in about it. Every archive stays right where it is: free leagues keep the core almanac on the UDFA tier, and the rest of the pages come with a plan.',
    status: 'new',
    tags: [{ label: 'Sitewide' }, { label: 'Pricing' }],
  },
  {
    id: 'the-weekly',
    date: 'Sep 15, 2026',
    title: 'The',
    titleEm: 'Weekly.',
    body: 'Your league’s whole week on one page, built for the group chat. Pick your name and it tells you whether your picks are in, who you’re playing, and where you rank, then runs the Pick’ems board, the power-ranking pecking order, the week’s trades, and which records and milestones are in play. Made for phones, opens anywhere, and shares with a preview card that lists what’s inside.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Live season' }, { label: 'Mobile' }],
  },
  {
    id: 'platform-status',
    date: 'Sep 10, 2026',
    title: 'Where the platforms',
    titleEm: 'stand.',
    body: 'NFL.com retired its fantasy platform in August, so new NFL.com imports are no longer possible. Every archive already built from it stays online and keeps working. Yahoo syncing is paused while we regain access to Yahoo’s fantasy API; existing Yahoo archives stay online and support is expected back soon. Sleeper and ESPN are fully live, history and in-season sync both.',
    status: 'new',
    tags: [{ label: 'Platforms', tone: 'steel' }],
  },
  {
    id: 'hand-entry',
    date: 'Sep 1, 2026',
    title: 'Type in the seasons',
    titleEm: 'no platform kept.',
    body: 'Commissioners can now paste a table or drop a CSV to add standings, drafts, or matchups by hand, with a live preview before anything saves. Team names match against every name a manager has ever used, and a hand-entered season is locked so a later sync can’t overwrite it. Syncs got safer across the board too: nothing is deleted until its replacement has arrived, and a sync that would hand a season to a completely different set of managers is stopped instead.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Almanac' }, { label: 'Commissioners' }],
  },
  {
    id: 'league-games',
    date: 'Aug 5, 2026',
    title: 'Games in every',
    titleEm: 'league.',
    body: 'The Games Page moved into each league’s almanac, so every game can be dealt out of your own league’s history with a leaderboard of its own. The games also got proper phone builds and a spot in the main menu.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Games' }, { label: 'Mobile' }],
  },
  {
    id: 'support-review',
    date: 'Aug 4, 2026',
    title: 'A line to',
    titleEm: 'the desk.',
    body: 'A support button now sits on every desktop almanac page and league settings page. Spot something wrong, write a line, and it comes straight to us. There’s a review page now too: a star rating plus a few optional questions on design, speed, and value, and a box for what you wish the site did.',
    status: 'new',
    tags: [{ label: 'Sitewide' }],
  },
  {
    id: 'multiverse-draft',
    date: 'Aug 3, 2026',
    title: 'The Multiverse',
    titleEm: 'Draft.',
    body: 'Game six. Every card is one player carrying up to three of the seasons your league actually rostered him, and each week he rolls one of them. Draft seven slots, play fourteen weeks against bot-drafted teams, and win eight to make a three-round postseason. Roster Roulette and the Multiverse Draft now keep leaderboards: best runs, a one-attempt weekly board where everyone plays the same deal, and a career board ranked by rate so volume can’t buy a spot.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Games' }],
  },
  {
    id: 'three-games',
    date: 'Aug 2, 2026',
    title: 'Three more',
    titleEm: 'games.',
    body: 'The Gauntlet: two teams, the week they met, who won? One wrong answer ends the run. The Over/Under: ten real team-weeks, each with a line, call it. Redraft: step into one manager’s real draft or the whole first round, and pick from a shortlist that always includes the player they actually took. All three run on your league’s own history.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Games' }],
  },
  {
    id: 'games-page',
    date: 'Jul 30, 2026',
    title: 'The Games',
    titleEm: 'Page.',
    body: 'A new back page for the paper. Roster Roulette spins up real teams from real seasons and you take one player off each, building a lineup that chases a 17-0 record. Guess the Draft shows a draft with the name and year blacked out, and you name the manager and the season. Play on your own league, on the Lakeside League demo, or, for Roulette, on every league on the site at once.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Games' }, { label: 'All members' }],
  },
  {
    id: 'link-previews',
    date: 'Jul 30, 2026',
    title: 'Link previews that',
    titleEm: 'look the part.',
    body: 'Every almanac page now sends its own preview card when you drop a link in the group chat: the Standings ledger, the Rivalries tally wall, the Draft report card, the Manager File, this week’s matchup slate, Milestones, Records Watch, and the season champions, each in its own page’s colors. The All-Time Team gets a trading-card display case of its own.',
    status: 'new',
    tags: [{ label: 'Sitewide' }],
  },
  {
    id: 'mobile-grader-alltime',
    date: 'Jul 29, 2026',
    title: 'The Grader and All-Time Team,',
    titleEm: 'on your phone.',
    body: 'Two of the newest Leagues rooms got real phone builds. The All-Time Team turns its trading cards sideways so the numbers stay readable, and the Draft Grader opens as a Grades tab with a transcript, the all-time best and worst picks, and a report card for every year. Both run on the same engine as desktop, so the grades always match. The Grader got retuned while we were in there: a full season of nothing no longer gets forgiven like an injury, and a player who missed time but produced gets partial credit.',
    status: 'new',
    tags: [{ label: 'New', tone: 'gold' }, { label: 'Leagues' }, { label: 'Mobile' }],
  },
  {
    id: 'standings-seating',
    date: 'Jul 29, 2026',
    title: 'Final standings that',
    titleEm: 'add up.',
    body: 'Some seasons showed two teams in 6th and nobody in 10th. Final standings are now seated a whole season at once: playoff teams in bracket order, everyone else by their regular-season finish, one place per team with no gaps and no repeats. Finished seasons also stop disappearing from the archive when a league still has them marked as the current season.',
    status: 'new',
    tags: [{ label: 'Almanac' }, { label: 'Fixes' }],
  },
  {
    id: 'hall-filters',
    date: 'Jul 21, 2026',
    title: 'The Hall gets',
    titleEm: 'filters.',
    body: 'The Clubhouse Hall of Records now filters by as many league formats as you like at once, with a quick 1-QB switch. A new Adjusted lens restates every points record against its own league’s average, so a high-scoring superflex league no longer owns every plaque on the wall.',
    status: 'new',
    tags: [{ label: 'Clubhouse' }, { label: 'Desktop', tone: 'steel' }],
  },
  {
    id: 'standard-superflex',
    date: 'Jul 21, 2026',
    title: 'Standard scoring and',
    titleEm: 'superflex.',
    body: 'Non-PPR leagues can now pick Standard scoring, so the All-Time Team and the Draft Grader score them properly instead of forcing a half-PPR fit. A new superflex switch in league settings adds an eighth slot to every All-Time Team.',
    status: 'new',
    tags: [{ label: 'Leagues' }],
  },
  {
    id: 'trade-room-clubhouse',
    date: 'Jul 20, 2026',
    title: 'The Trade Room, rebuilt in',
    titleEm: 'the Clubhouse.',
    body: 'The Clubhouse Trade Analyzer was reworked to match the league desk exactly. Name the two sides, pick your format, and it grades the deal off the same consensus value engine, now resolving players across every platform instead of one. Post the close ones to the docket, let the room regrade them, and vote on who won.',
    status: 'new',
    tags: [{ label: 'Clubhouse' }, { label: 'All members' }],
  },
  {
    id: 'trade-desk-overhaul',
    date: 'Jul 19, 2026',
    title: 'A sharper',
    titleEm: 'Trade Desk.',
    body: 'The league Trade Desk got an accuracy pass from end to end. Values now respect your league’s scoring and TE premium, the Grader reads players off any of the four platforms and prices them from the consensus engine, and executed trades grade themselves every day with a four-week revisit. The Grader room itself was redrawn as a wire room: the season’s biggest deal runs as a full front page, and the rest fall down a dated timeline.',
    status: 'new',
    tags: [{ label: 'Live season' }, { label: 'Trade Desk' }],
  },
  {
    id: 'broadsheet-landing',
    date: 'Jul 19, 2026',
    title: 'A brand new',
    titleEm: 'front page.',
    body: 'The whole landing page was rebuilt as a proper broadsheet: the pitch, the four platforms, the pages, and the pricing all set like the front of a newspaper. It is the first thing a new commissioner sees, and now it finally looks the part.',
    status: 'new',
    tags: [{ label: 'Sitewide' }],
  },
  {
    id: 'leagues-wing',
    date: 'Jul 15, 2026',
    title: 'Four new rooms in the',
    titleEm: 'Leagues wing.',
    body: 'The almanac grew a whole floor. The <em>Draft Grader</em> scores every draft class you have ever run and stacks the managers on a report card. The <em>All-Time Team</em> builds each manager’s best-ever starting lineup as a deck of trading cards. The <em>Chart Room</em> draws twelve hand-inked charts of a manager’s entire career. And the <em>Mock Room</em> runs a full snake-draft simulator against ghost managers modeled on how your league actually drafts.',
    status: 'new',
    tags: [{ label: 'Leagues' }, { label: 'Desktop', tone: 'steel' }],
  },
  {
    id: 'standings-archives',
    date: 'Jul 12, 2026',
    title: 'Standings and Archives,',
    titleEm: 'rebuilt.',
    body: 'The all-time standings, the season archives, and every single-season page were rebuilt from the ground up. Cleaner tables, faster reads, and season exports now carry full week-by-week matchup history, so the record book and the recaps have more to draw on.',
    status: 'new',
    tags: [{ label: 'Almanac' }, { label: 'Desktop', tone: 'steel' }],
  },
  {
    id: 'league-setup',
    date: 'Jul 8, 2026',
    title: 'A smoother league',
    titleEm: 'setup.',
    body: 'Adding a league got a new preview and setup screen. Point it at your league on any platform, see exactly what history will come back before you commit, and get into the almanac faster.',
    status: 'new',
    tags: [{ label: 'Sitewide' }],
  },
  {
    id: 'record-book-remix',
    date: 'Jun 30, 2026',
    title: 'The Record Book,',
    titleEm: 'reimagined.',
    body: 'The record book was rebuilt as a set of swipeable rails with a podium for every stat, so first, second, and third all get called out, not just the leader. New title-era records joined the board, and the whole thing now reads like a mosaic of feats instead of a flat list.',
    status: 'new',
    tags: [{ label: 'Almanac' }],
  },
  {
    id: 'guides-shelf',
    date: 'Jun 20, 2026',
    title: 'A bigger Guides',
    titleEm: 'shelf.',
    body: 'New deep-dives on the Trade Analyzer, Milestone Tracker, manager analysis, league-management software, league-history software, the Recap, the Almanac, and a fresh league setup walkthrough. The Guides page itself got a browsable shelf so you can compare and filter instead of scrolling a flat list.',
    status: 'new',
    tags: [{ label: 'Guides' }],
  },
  {
    id: 'mobile-rework',
    date: 'Jun 18, 2026',
    title: 'A mobile rework, top to',
    titleEm: 'bottom.',
    body: 'Every page on TSC got a phone-native rebuild: landing, Clubhouse, dashboard, league shells, almanac, live season, pricing, guides, the manager and rivalry pages. Simpler chrome, denser cards, one-thumb navigation, and a dedicated mobile tree (separate from desktop) so the small screen never inherits a layout it can’t carry. Open the site on a phone and it should finally feel like one.',
    status: 'new',
    tags: [{ label: 'Mobile' }, { label: 'Sitewide' }],
  },
  {
    id: 'trade-room',
    date: 'Jun 10, 2026',
    title: 'The Trade Room opens in',
    titleEm: 'the Clubhouse.',
    body: 'The Trade Analyzer, unchained from the league: name the players on each side, pick the format (redraft or dynasty, 1-QB or superflex), and the same consensus value engine renders a verdict; add both full rosters and it grades real starting-lineup impact instead. Post the contentious ones to the docket and let the room vote on who won.',
    status: 'new',
    tags: [{ label: 'Clubhouse' }, { label: 'All members' }],
  },
  {
    id: 'trade-desk',
    date: 'Jun 9, 2026',
    title: 'The Trade Desk opens',
    titleEm: 'four rooms.',
    body: 'The Grader scores every executed deal and revisits it four weeks later. The Analyzer stress-tests a deal before you send it. The Finder shops your players or hunts a target with real package suggestions. And the Rumor Mill invents a fresh slate of plausible mock trades for your league every week. Argue accordingly.',
    status: 'new',
    tags: [{ label: 'Live season' }, { label: 'All plans' }],
  },
  {
    id: 'udfa',
    date: 'Jun 6, 2026',
    title: 'The free tier:',
    titleEm: 'UDFA.',
    body: 'Every account now carries one free trial league with every paid page unlocked; your earliest league gets the slot automatically. Additional free leagues keep the core almanac: all-time standings, rivalries, and the manager strip.',
    status: 'new',
    tags: [{ label: 'Pricing' }],
  },
  {
    id: 'manager-dna',
    date: 'Jun 5, 2026',
    title: 'Manager',
    titleEm: 'DNA.',
    body: 'Waiver habits, trade volume, draft tendencies, lineup churn: dozens of signals distilled into one archetype per manager, with the receipts to back it up. The Census page in this very Clubhouse runs the same idea across the whole network.',
    status: 'new',
    tags: [{ label: 'Live season' }],
  },
  {
    id: 'best-coach',
    date: 'Jun 2, 2026',
    title: 'The Best Coach',
    titleEm: 'Tracker.',
    body: 'Optimal-lineup math for every week of the season: who squeezed the most from their roster, who left a win on the bench, and a Hall of Shame for the worst sit-start calls on file.',
    status: 'new',
    tags: [{ label: 'Live season' }],
  },
  {
    id: 'matchup-preview',
    date: 'Jun 1, 2026',
    title: 'Matchup',
    titleEm: 'Preview.',
    body: 'A departures board for the week ahead: every matchup with all-time head-to-head history, last-five form, and projections. Click through to any manager’s desk for the full dossier.',
    status: 'new',
    tags: [{ label: 'Live season' }],
  },
  {
    id: 'yahoo-nfl',
    date: 'May 31, 2026',
    title: 'Yahoo and NFL.com',
    titleEm: 'join the press.',
    body: 'TSC now ingests league history from all four major platforms: Sleeper, ESPN, Yahoo, and NFL.com. Same archive, same record book, whichever app your league calls home.',
    status: 'new',
    tags: [{ label: 'Platforms', tone: 'steel' }],
  },
  {
    id: 'records-watch',
    date: 'May 2026',
    title: 'Records Watch &',
    titleEm: 'Milestones.',
    body: 'The live hub tracks which franchise records are in danger this week and which round-number milestones are about to fall, so the chase gets called before it happens, not after.',
    status: 'new',
    tags: [{ label: 'Live season' }],
  },
]
