// The record: turning a lineup's PPG into a season.
//
// Two fixed numbers per scoring profile, generated by
// scripts/build-minigame-benchmark.mjs and shown to the player up front:
//
//   target — the PPG a lineup must be worth to go 17-0
//   floor  — the PPG below which it goes 0-17
//
// Wins scale linearly between them. The bar is a stated constant, not a
// percentile against the run itself: you are chasing a number you can see
// before you spin, and two people playing different wheels are chasing the
// same one.
//
// The constants are derived from simulation (target = 90th percentile of
// perfect play, floor = 10th percentile of ordinary play), which puts median
// play near .500, perfect play on an average wheel around 10-7, and 17-0
// within reach only when a good wheel is played without a mistake.
//
// Pure by design: the client imports this to score a lineup as it's built,
// so nothing here may touch the filesystem. Reading the file these run
// against is benchmarkFile.ts's job, server-side.

export const GAMES = 17

export type Benchmark = {
  profile: string
  /** PPG needed for 17-0. */
  target: number
  /** PPG at or below which the lineup goes 0-17. */
  floor: number
  /** What a typical run is worth, for context. */
  medianPlay: number
}

/** Wins out of 17 for a lineup worth `ppg` per week. */
export function recordFor(ppg: number, benchmark: Benchmark | null): number {
  if (!benchmark) return 0
  const { floor, target } = benchmark
  if (target <= floor) return 0
  const share = (ppg - floor) / (target - floor)
  return Math.max(0, Math.min(GAMES, Math.round(share * GAMES)))
}

/** How the season reads on the back page. */
export function recordHeadline(wins: number): string {
  const losses = GAMES - wins
  if (wins === GAMES) return 'Perfect season. Nobody beat you.'
  if (wins >= 15) return 'A bye and a banner.'
  if (wins >= 13) return 'Top seed. Comfortably.'
  if (wins >= 11) return 'That team is making a run.'
  if (wins >= 9) return 'You are in the playoff hunt.'
  if (wins === 8 && losses === 9) return 'One game under. Painful.'
  if (wins >= 6) return 'Lottery team.'
  if (wins >= 3) return 'That is a rebuild.'
  if (wins >= 1) return 'At least you won one.'
  return 'Winless. Genuinely impressive in its own way.'
}
